mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml # mapper文件路径
  type-aliases-package: com.example.base.pojo # 实体类路径
server:
  address: 127.0.0.1 # 服务器地址
  port: 9999 # 端口号
spring:
  application:
    name: sm # 服务名称
  datasource:
    # Mysql 数据库连接池配置
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    # username: root
    # password: 123456
    # sqlite 数据库
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:demo.db
    username:
    password:
logging:
  level:
    com.example.dao : debug # 日志级别